#!/usr/bin/env bash

# Author: Barret E <https://github.com/archusXIV>
# Create g810-led colorschemes (profiles) from a skeleton file: manually,
# from our current ~/.Xresources colors or from an existing Xresources theme.
# supported keyboard: G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro,

# shellcheck disable=SC2024
myModelName=$(awk '/Keyboard/{print $9}' < <(lsusb))
myModelBinary="${myModelName,}-led"

! grep -q "$myModelName" < <(lsusb) && {
    [[ -z $(command -v "$myModelBinary") ]] && {
        echo " No g810-led related binary found...exiting"
        exit 127
    }
    echo "Keyboard $myModelName is not plugged in, exiting..."
    exit 1
}

config_dir="$HOME/.config/g810-led"
profiles_dir="$config_dir/profiles"
keys_skel="$config_dir/keys_skel"
groups_skel="$config_dir/groups_skel"
themes_dir="$config_dir/themes"
etc_confdir="/etc/g810-led"
etc_profiles="/etc/g810-led/profiles"

declare -a XresourcesColors=(
    color1 color2 color3 color4 color5 color6 color7
)

# ~/.config/g810-led/themes/<myTheme> [variables] names
declare -A ThemeColors=(
    [red]="${XresourcesColors[0]}"
    [grn]="${XresourcesColors[1]}"
    [ylw]="${XresourcesColors[2]}"
    [blu]="${XresourcesColors[3]}"
    [mag]="${XresourcesColors[4]}"
    [cyn]="${XresourcesColors[5]}"
    [wht]="${XresourcesColors[6]}"
)

cd "$profiles_dir" || exit 1

_main() {
    local profile_name profile_type colorvalue colorname

    read -rp " create a [G]roup or a [K]eys profile? " profile_type
    read -rp " create [M]anually, from a [T]heme or from [X]resources: " create_from
    printf '\n'
    case "$create_from" in
        m|M)
            _ifProfileNameAlreadyExist
            _ifProfileTypeIs
            for colorname in "${XresourcesColors[@]}"; do
                printf '\n'
                printf '%s\n' " ${G}color1=red color2=green color3=yellow color4=blue " \
                              " color5=magenta color6=cyan color7=white${Z}"
                printf '\n'
                read -rp " ${G}Enter an hex color value for $colorname: ${Z}" colorvalue
                [[ ! $colorvalue =~ ^[a-fA-F0-9]{6}$ ]] && {
                    printf '%s\n' " ${R}Hex colors must be 6 digits/numbers!" \
                    " 0 -> 9, a -> f, eg: 88def2${Z}"
                    rm "$profile_name"
                    sleep 2
                    exit 1
                }
                sed -i "s/var ${colorname}/var ${colorname} ${colorvalue}/" "$profile_name"
                clear
            done
        ;;
        t|T)
            if [[ -d $themes_dir ]]; then
                PS3=""$'\n'" Choose an existing theme: "
                select profile_name in $(find "$themes_dir" -type f -printf '%f\n' | sort); do
                    _ifProfileTypeIs
                    for key in "${!ThemeColors[@]}"; do
                        colorname="${ThemeColors[${key}]}"
                        colorvalue=$(
                            awk -F'#' -v K="$key" '$0~K{print $3; exit}
                            ' "$themes_dir/$profile_name"
                        )
                        printf '%s\n' "$colorvalue"
                        sed -i "s/var ${colorname}/var ${colorname} ${colorvalue}/" \
                        "$profile_name"
                    done
                    break
                done
            else
                printf '%s\n' " $themes_dir does not exist...exiting"
                exit 1
            fi
        ;;
        x|X)
            if [[ -e $HOME/.Xresources ]]; then
                _ifProfileNameAlreadyExist
                _ifProfileTypeIs
                for x in "${XresourcesColors[@]}"; do
                    colorvalue=$(xrdb -query | awk -F'#' -v X="$x" '$0 ~ X { print $2; exit }')
                    printf '%s\n' "$colorvalue"
                    sed -i "s/var ${x}/var ${x} ${colorvalue}/" "$profile_name"
                done
            else
                printf '%s\n' " $HOME/.Xresources does not exist...exiting"
                exit 1
            fi
        ;;
        *)
            printf '%s\n' " Wrong option '$create_from'...exiting"
            exit 1
        ;;
    esac
    _saveAs
}

_ifProfileTypeIs() {
    case "${profile_type}" in
        [gG])
            cp "$groups_skel" "$profiles_dir/$profile_name"
            sed -i "1s/^/# $profile_name\n/" "$profile_name"
        ;;
        [kK])
            cp "$keys_skel" "$profiles_dir/$profile_name"
            sed -i "1s/^/# $profile_name\n/" "$profile_name"
        ;;
        [cC])
            printf '%s\n' " ${R}Selection cancelled...${Z}"
            sleep 2
            _mainMenu
        ;;
        *)
            printf '%s\n' " ${R}Wrong option $profile_type.${Z}"
            sleep 2
            _mainMenu
        ;;
    esac
    clear
}

_ifProfileNameAlreadyExist() {
    read -rp " ${G}Enter a profile name: ${Z}" profile_name
    [[ -f $profiles_dir/$profile_name ]] && {
        printf '%s\n' " ${R}profile $profile_name already exists, try again...${Z}"
        sleep 2
        clear
        exit 1
    }
}

_saveAs() {
    sudo mkdir -p "$etc_profiles"
    sudo cp -f "$profile_name" "$etc_profiles/$profile_name"
    sudo chmod +r "$etc_profiles/$profile_name"
    read -rp " Apply $profile_name? [Y/n]: "
    case "$REPLY" in
        [yY])
            sudo "$myModelBinary" -pp < "$etc_profiles/$profile_name"
            sudo cp -f "$etc_profiles/$profile_name" "$etc_confdir"/profile
        ;; [nN]) exit 0 ;;
        *) echo " wrong option $REPLY...exiting" && exit 1 ;;
    esac
}

_main "${@}"