#!/bin/bash

# Author: Barret E <https://github.com/archusXIV>
# Usage: g810_switch_profile <profile_name>
#    or: g810_switch_profile (no argument & we'll get a menu)
# Fill the myModelName variable with your supported keyboard.
# G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro,
# use lsusb to find out your model name & model id

myModelName=G815
myModelId=c33f

! grep -q "$myModelName" < <(lsusb) && {

    [[ -z $(command -v g810-led) ]] && {
        echo " g810-led not found...exiting"
        exit 127
    }

    echo "$myModelName is not plugged in, exiting..."
    exit 1
    
}

profiles_dir="$HOME/.config/g810-led/profiles"
cd "$profiles_dir" || exit 1

rules="/etc/udev/rules.d/g810-led.rules"
profile=$(grep -e "$myModelId" "$rules" | sed 's,.*/,,;s/"//')
profile_name="$1"

if [[ -f profile_$1 ]]; then

    g810-led -pp < profile_"$profile_name"
    sudo sed -i "s/${profile}/profile_${profile_name}/" "$rules"
	
elif [[ ! -f profile_$1 ]]; then
	
	[[ -z $1 ]] && echo -e " no argument given...\n" || \
	echo -e " $1 does not exist.\n"

	awk -v ID="$myModelId" -v PRFL="$profile" '
		$0~ID{
			gsub("/","")
			sub("[\"]","")
			}
		{ print " In use "PRFL": "; exit }
	' "$rules" | sed 's/profile_//'
	printf '\n'

	PS3=""$'\n'" Choose a RGB profile: "
    select name in $(
			find . \
			-type f \
			-name "profile_*" \
			| sort \
			| sed 's,.*/,,;s/profile_//'
		); do

	    g810-led -pp < profile_"$name"
	    sudo sed -i "s/${profile}/profile_${name}/" \
	    "$rules"
		echo " profile $name selected."
	    break

    done
fi
