#!/usr/bin/env bash

# Author: Barret E <https://github.com/archusXIV>
#
# This script let us delete RGB profiles designed to be use with our
# Logitech compatible keyboard.
# First install the g810-led package from sources or the AUR repository.
# Supported keyboards: G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro
# use lsusb | grep -i keyboard, to find out your model name & model id
# Usage: g810_delete_profile <profile_name>
#    or: g810_delete_profile (no argument & we'll get a menu)

# shellcheck disable=SC2024
[[ ! $(awk '/Keyboard/{print $7}' < <(lsusb)) =~ ^Logitech,$ ]] && {
    printf '%s\n' " ${R}No Logitech keyboard detected, exiting...${Z}"
    exit 1
}

declare -a Keyboards=( G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro )
for keyboard in "${Keyboards[@]}"; do
    if [[ $(awk '/Keyboard/{print $9}' < <(lsusb)) != "$keyboard" ]]; then
        continue
    else
        myModelName="$keyboard"
    fi
done

myModelBinary="${myModelName,}-led"
command -v "$myModelBinary" || {
    printf '%s\n' " ${R}No g810-led related binary found...exiting${Z}"
    exit 127
}

etc_confdir="/etc/g810-led"
config_profiles="$HOME/.config/g810-led/profiles"
profile=$(sed -n '1s/# //p' "$etc_confdir"/profile)
cd "$etc_confdir/profiles" || exit 1

if [[ $1 = default ]]; then
    echo "You cannot delete default profile..." && exit 1
elif [[ $1 = "$profile" ]]; then
    profile_name="$1"
    sudo "$myModelBinary" -pp < default
    sudo cp -f default "$etc_confdir"/profile
    sudo rm "$profile_name"
    rm "$config_profiles/$profile_name"
    echo " profile $1 deleted."
elif [[ $1 != "$profile" ]]; then
    [[ -z $1 ]] && echo -e " no argument given...\n" || \
    echo -e " $1 does not exist.\n"
    printf '\n'
    PS3=""$'\n'" Choose a RGB profile to delete: "
    select profile_name in $(find . -type f -not -name "default" -printf '%f\n' | sort); do
        if [[ $profile_name == "$profile" ]]; then
            sudo "$myModelBinary" -pp < default
            sudo cp -f default "$etc_confdir"/profile
            sudo rm "$profile_name"
            rm "$config_profiles/$profile_name"
            echo " profile $profile_name deleted."
        else
            sudo rm "$profile_name"
            rm "$config_profiles/$profile_name"
            echo " profile $profile_name deleted."
        fi
        break
    done
fi
