#!/usr/bin/env bash

# Author: Barret E <https://github.com/archusXIV>
# Usage: g810_delete_profile <profile_name>
#    or: g810_delete_profile (no argument & we'll get a menu)
# supported keyboard: G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro

# shellcheck disable=SC2024
myModelName=$(awk '/Keyboard/{print $9}' < <(lsusb))
myModelBinary="${myModelName,}-led"

! grep -q "$myModelName" < <(lsusb) && {
    [[ -z $(command -v "$myModelBinary") ]] && {
        printf '%s\n' " No g810-led related binary found...exiting"
        exit 127
    }
    printf '%s\n' "$myModelName is not plugged in, exiting..."
    exit 1
}

etc_confdir="/etc/g810-led"
config_profiles="$HOME/.config/g810-led/profiles"
profile=$(sed -n '1s/# //p' "$etc_confdir"/profile)
cd "$etc_confdir/profiles" || exit 1

if [[ $1 = default ]]; then
    printf '%s\n' "You cannot delete default profile..." && exit 1
elif [[ $1 = "$profile" ]]; then
    profile_name="$1"
    sudo "$myModelBinary" -pp < default
    sudo cp -f default "$etc_confdir"/profile
    sudo rm "$profile_name"
    rm "$config_profiles/$profile_name"
    printf '%s\n' " profile $1 deleted."
elif [[ $1 != "$profile" ]]; then
    [[ -z $1 ]] && printf '%s\n' " no argument given..." || \
    printf '%s\n' " $1 does not exist."
    printf '\n'
    PS3=""$'\n'" Choose a RGB profile to delete: "
    select profile_name in $(find . -type f -not -name "default" -printf '%f\n' | sort); do
        if [[ $profile_name == "$profile" ]]; then
            sudo "$myModelBinary" -pp < default
            sudo cp -f default "$etc_confdir"/profile
            sudo rm "$profile_name"
            rm "$config_profiles/$profile_name"
            printf '%s\n' " profile $profile_name deleted."
        else
            sudo rm "$profile_name"
            rm "$config_profiles/$profile_name"
            printf '%s\n' " profile $profile_name deleted."
        fi
        break
    done
fi
