#!/usr/bin/env bash

# Author: Barret E <https://github.com/archusXIV>
# Usage: g810_switch_profile <profile_name>
#    or: g810_switch_profile (no argument & we'll get a menu)
# supported keyboard: G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro

# shellcheck disable=SC2024
myModelName=$(awk '/Keyboard/{print $9}' < <(lsusb))
myModelBinary="${myModelName,}-led"

! grep -q "$myModelName" < <(lsusb) && {
    [[ -z $(command -v "$myModelBinary") ]] && {
        echo " No g810-led related binary found...exiting"
        exit 127
    }
    echo "Keyboard $myModelName is not plugged in, exiting..."
    exit 1
}

etc_confdir="/etc/g810-led"
etc_profiles="$etc_confdir/profiles"
profile=$(sed -n '1s/# //p' "$etc_confdir"/profile)
cd "$HOME/.config/g810-led/profiles" || exit 1

if [[ -f $1 ]]; then
    profile_name="$1"
    sudo "$myModelBinary" -pp < "$profile_name"
    sudo cp -f "$etc_profiles/$profile_name" "$etc_confdir"/profile
elif [[ ! -f $1 ]]; then
    [[ -z $1 ]] && echo -e " no argument given...\n" || \
    echo -e " $1 does not exist.\n"
    printf '%s\n' " In use $profile"
    printf '\n'
    PS3=""$'\n'" Choose a RGB profile: "
    select profile_name in $(find . -type f -printf '%f\n' | sort); do
        sudo "$myModelBinary" -pp < "$profile_name"
        sudo cp -f "$etc_profiles/$profile_name" "$etc_confdir"/profile
        echo " profile $profile_name selected."
        break
    done
fi
